/**
 * CLI: init - 하네스 플러그인 설치 파일 생성
 *
 * 작성자: 최진호
 * 작성일: 2026-10-03
 *
 * integrations/의 Claude Code 또는 Codex 플러그인을 로컬 마켓플레이스 디렉터리 형태로 만든다.
 * 기본은 dry-run이다: 만들 파일 목록과 diff만 출력한다. --write를 주어야 쓰고, 내용이 다른 기존 파일은
 * --force 없이 덮어쓰지 않는다. --dir 아래 경로의 어느 조각이든 심볼릭 링크이거나, 최종 경로가 일반 파일이
 * 아니면 언제나 거부한다. 쓰기는 먼저 모든 위치의 쓰기 권한을 확인하고, 파일마다 임시 파일과 rename으로
 * 바꾸며, 도중에 실패하면 이번 실행의 변경을 되돌린다(_fileTransaction.js).
 *
 * API 키는 어떤 파일에도 쓰지 않는다. Claude Code 플러그인은 키를 sensitive userConfig로 받아 보안
 * 저장소에 두고, Codex는 환경 변수 이름(bearer_token_env_var)만 설정한다. 이 모듈은 lib/config.js와
 * dotenv를 가져오지 않으므로 .env를 읽지 않으며, 환경 변수를 읽지 않는다. PATH 경고에 쓰는 PATH 값은
 * 진입점이 넘기며 생성 내용에는 영향이 없다.
 */

import fs                from "node:fs";
import os                from "node:os";
import path              from "node:path";
import { fileURLToPath } from "node:url";

import { diffLines }                                                   from "./_lineDiff.js";
import { createOutput }                                                from "./_stdout.js";
import { FileTransactionError, inspectUnder, unwritableTargets, writeAll } from "./_fileTransaction.js";

export const usage = [
  "Usage: anchormind init --target <claude|codex> [--dir <path>] [--url <mcp-url>] [--write] [--force]",
  "",
  "Create the AnchorMind plugin for Claude Code or Codex as a local plugin marketplace directory.",
  "Without --write it only prints the files it would create and a diff against existing files.",
  "",
  "Options:",
  "  --target <name>   claude | codex",
  "  --dir <path>      marketplace directory (default: ~/.anchormind/claude-code or ~/.anchormind/codex)",
  "  --url <URL>       MCP server URL shown in the Codex config.toml snippet",
  "  --write           write the files",
  "  --force           with --write, replace existing files whose content differs",
  "",
  "The API key is never written to a file. Claude Code asks for it when the plugin is enabled and keeps it",
  "in the secure credential store; Codex reads it from the MEMENTO_CLI_KEY environment variable.",
].join("\n");

/** init 인자와 파일 상태 오류 */
export class InitError extends Error {
  constructor(message) {
    super(message);
    this.name = "InitError";
  }
}

const PLUGIN_NAME      = "anchormind";
const MARKETPLACE_NAME = "anchormind-local";
const PLUGIN_DIR       = `plugins/${PLUGIN_NAME}`;
const PLACEHOLDER_URL  = "https://memento.example.com/mcp";
const KEY_ENV          = "MEMENTO_CLI_KEY";
const REMOTE_ENV       = "MEMENTO_CLI_REMOTE";
const INTEGRATIONS     = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "integrations");

/**
 * 대상별 정의. source는 integrations/ 아래 플러그인 디렉터리, homeDir은 --dir 기본값의 마지막 조각이다.
 */
export const INIT_TARGETS = Object.freeze({
  claude: Object.freeze({ source: "claude-code", homeDir: "claude-code", marketplace: claudeMarketplace, nextSteps: claudeNextSteps }),
  codex : Object.freeze({ source: "codex",       homeDir: "codex",       marketplace: codexMarketplace,  nextSteps: codexNextSteps })
});

/** JSON 파일 내용(2칸 들여쓰기, 끝 줄바꿈) */
const toJson = (value) => `${JSON.stringify(value, null, 2)}\n`;

/**
 * @param {object} plugin Claude Code plugin.json
 * @returns {{ path: string, content: string }}
 */
function claudeMarketplace(plugin) {
  return {
    path   : ".claude-plugin/marketplace.json",
    content: toJson({
      name       : MARKETPLACE_NAME,
      owner      : { name: plugin.author.name },
      description: "AnchorMind plugin generated by anchormind init",
      plugins    : [{ name: PLUGIN_NAME, source: `./${PLUGIN_DIR}`, description: plugin.description }]
    })
  };
}

/**
 * @returns {{ path: string, content: string }}
 */
function codexMarketplace() {
  return {
    path   : ".agents/plugins/marketplace.json",
    content: toJson({
      name     : MARKETPLACE_NAME,
      interface: { displayName: "AnchorMind" },
      plugins  : [{
        name    : PLUGIN_NAME,
        source  : { source: "local", path: `./${PLUGIN_DIR}` },
        policy  : { installation: "AVAILABLE", authentication: "ON_INSTALL" },
        category: "Productivity"
      }]
    })
  };
}

/**
 * @param {{ dir: string }} ctx
 * @returns {string[]}
 */
function claudeNextSteps({ dir }) {
  return [
    `claude plugin marketplace add ${dir}`,
    `claude plugin install ${PLUGIN_NAME}@${MARKETPLACE_NAME}`,
    "Claude Code asks for server_url and api_key when the plugin is enabled. The key goes to the secure credential store.",
    "The hooks run `anchormind hook`: put anchormind on PATH (npm link in the repository, or a global install)."
  ];
}

/**
 * @param {{ dir: string, url: string }} ctx
 * @returns {string[]}
 */
function codexNextSteps({ dir, url }) {
  return [
    `codex plugin marketplace add ${dir}`,
    `codex plugin add ${PLUGIN_NAME}@${MARKETPLACE_NAME}`,
    "Then review and trust the plugin hooks with /hooks in Codex.",
    "Add the MCP server to ~/.codex/config.toml. Only the environment variable name is written:",
    "  [mcp_servers.anchormind]",
    `  url = "${url}"`,
    `  bearer_token_env_var = "${KEY_ENV}"`,
    `  (or: codex mcp add anchormind --url ${url} --bearer-token-env-var ${KEY_ENV})`,
    `Export ${REMOTE_ENV} and ${KEY_ENV} in the environment Codex starts from. The hooks read them.`,
    "The hooks run `anchormind hook`: put anchormind on PATH (npm link in the repository, or a global install)."
  ];
}

/**
 * 대상 정의. 모르는 대상이면 InitError.
 *
 * @param {unknown} target
 * @returns {object}
 */
function targetSpec(target) {
  if (typeof target === "string" && Object.hasOwn(INIT_TARGETS, target)) return INIT_TARGETS[target];
  throw new InitError(`--target must be one of ${Object.keys(INIT_TARGETS).join(", ")}`);
}

/**
 * 플러그인 원본 디렉터리의 파일(상대 경로, / 구분)
 *
 * @param {string} sourceDir
 * @returns {string[]}
 */
function templateFiles(sourceDir) {
  return fs.readdirSync(sourceDir, { recursive: true, withFileTypes: true })
    .filter(entry => entry.isFile())
    .map(entry => path.relative(sourceDir, path.join(entry.parentPath, entry.name)).split(path.sep).join("/"))
    .sort();
}

/**
 * --url 검사. 자격 증명이 든 주소와 http(s)가 아닌 주소는 받지 않는다.
 *
 * @param {unknown} url
 * @returns {string}
 */
function checkUrl(url) {
  if (url === undefined) return PLACEHOLDER_URL;
  let parsed;
  try {
    parsed = new URL(String(url));
  } catch {
    throw new InitError("--url must be an absolute URL");
  }
  if (parsed.protocol !== "https:" && parsed.protocol !== "http:") throw new InitError("--url must use https or http");
  if (parsed.username || parsed.password) throw new InitError("--url must not contain credentials");
  return parsed.href;
}

/**
 * 만들 파일 목록과 다음 단계 안내. 파일 시스템에는 integrations/ 원본을 읽기만 한다.
 *
 * @param {{ target: string, dir: string, url?: string }} options
 * @returns {{ target: string, dir: string, files: Array<{ path: string, content: string }>, nextSteps: string[] }}
 */
export function planInit({ target, dir, url }) {
  const spec      = targetSpec(target);
  const mcpUrl    = checkUrl(url);
  const sourceDir = path.join(INTEGRATIONS, spec.source);
  const plugin    = templateFiles(sourceDir).map(rel => ({
    path   : `${PLUGIN_DIR}/${rel}`,
    content: fs.readFileSync(path.join(sourceDir, rel), "utf8")
  }));
  const manifest  = plugin.find(f => /(^|\/)plugin\.json$/.test(f.path));
  const files     = [spec.marketplace(JSON.parse(manifest.content)), ...plugin];
  return { target, dir, files, nextSteps: spec.nextSteps({ dir, url: mcpUrl }) };
}

/**
 * --dir의 실제 경로. 없으면 해석한 절대 경로(그 아래에는 아직 아무것도 없다), 디렉터리가 아니면 InitError.
 *
 * @param {string} dir
 * @returns {string}
 */
function resolveRoot(dir) {
  let stat;
  try {
    stat = fs.statSync(dir);
  } catch (err) {
    if (err.code === "ENOENT") return path.resolve(dir);
    throw err;
  }
  if (!stat.isDirectory()) throw new InitError(`--dir is not a directory: ${dir}`);
  return fs.realpathSync(dir);
}

/**
 * 계획한 파일을 디스크와 비교한다. 경로의 어느 조각이든 심볼릭 링크면 막힌 경로다.
 *
 * @param {{ dir: string, files: Array<{ path: string, content: string }> }} plan
 * @returns {Array<{ path: string, absPath: string, content: string, status: string, existing: string, reason?: string }>}
 */
function compareWithDisk(plan) {
  const root = resolveRoot(plan.dir);
  return plan.files.map((file) => {
    const absPath = path.resolve(root, ...file.path.split("/"));
    if (!absPath.startsWith(root + path.sep)) throw new InitError(`${file.path} resolves outside --dir`);
    const found  = inspectUnder(root, file.path);
    const status = found.kind === "missing" ? "create"
      : found.kind === "blocked" ? "blocked"
        : found.content === file.content ? "unchanged" : "conflict";
    return { ...file, absPath, status, existing: found.content ?? "", reason: found.reason };
  });
}

/**
 * 상태별 요약 줄의 덧붙임 설명
 *
 * @param {{ status: string, reason?: string }} entry
 * @returns {string}
 */
function statusNote(entry) {
  if (entry.status === "conflict") return "  (exists with different content; --force replaces it)";
  if (entry.status === "blocked")  return `  (${entry.reason}; not written)`;
  return "";
}

/**
 * 요약과 diff 출력 줄
 *
 * @param {Array<object>} entries
 * @returns {string[]}
 */
function renderReport(entries) {
  const lines = entries.map(e => `  ${e.status.padEnd(10)} ${e.path}${statusNote(e)}`);
  for (const entry of entries.filter(e => e.status === "create" || e.status === "conflict")) {
    lines.push("", entry.status === "create" ? "--- /dev/null" : `--- ${entry.path} (existing)`, `+++ ${entry.path}`);
    for (const { op, line } of diffLines(entry.existing, entry.content)) lines.push(`${op}${line}`);
  }
  return lines;
}

/**
 * 쓰기 전 검사. 막힌 경로가 있거나, --force 없이 충돌이 있거나, 쓸 위치에 쓰기 권한이 없으면 아무것도
 * 쓰지 않고 실패한다.
 *
 * @param {Array<object>} entries
 * @param {boolean} force
 * @param {object} ops fs 함수 묶음
 */
function assertWritable(entries, force, ops) {
  const blocked   = entries.filter(e => e.status === "blocked").map(e => `${e.path} (${e.reason})`);
  const conflicts = entries.filter(e => e.status === "conflict").map(e => e.path);
  if (blocked.length > 0) throw new InitError(`refusing to write through or over: ${blocked.join(", ")}`);
  if (conflicts.length > 0 && !force) {
    throw new InitError(`existing files differ (use --force to replace): ${conflicts.join(", ")}`);
  }
  const denied = unwritableTargets(entries.filter(isPending), ops);
  if (denied.length > 0) {
    throw new InitError(`not writable, nothing was written: ${denied.join(", ")}. Fix the directory permissions and run the command again`);
  }
}

/** 이번 실행이 쓸 항목 */
const isPending = (entry) => entry.status === "create" || entry.status === "conflict";

/**
 * 만들 파일과 덮어쓸 파일을 쓴다. 실패하면 이번 실행의 변경을 되돌리고 InitError를 던진다.
 *
 * @param {Array<object>} entries
 * @param {object} ops
 * @returns {number} 쓴 파일 수
 */
function writeEntries(entries, ops) {
  try {
    return writeAll(entries.filter(isPending), ops);
  } catch (err) {
    if (!(err instanceof FileTransactionError)) throw err;
    const left = err.leftovers.length > 0
      ? ` Could not undo: ${err.leftovers.join(", ")}; remove or restore these by hand.`
      : " Files created by this run were removed and replaced files were restored.";
    throw new InitError(`write failed at ${err.path} (${err.code ?? err.cause?.message}).${left} Fix the cause and run the command again.`);
  }
}

/**
 * 실행 파일 이름이 PATH 디렉터리 중 하나에 있는지 본다. Windows는 PATHEXT 확장자를 붙여 본다.
 *
 * @param {string} name
 * @param {string} searchPath PATH 값
 * @param {string} pathExt PATHEXT 값(Windows 밖에서는 빈 문자열)
 * @returns {boolean}
 */
export function onPath(name, searchPath, pathExt) {
  const exts = ["", ...pathExt.split(";").filter(Boolean)];
  return searchPath.split(path.delimiter).filter(Boolean).some(dir =>
    exts.some((ext) => {
      try {
        return fs.statSync(path.join(dir, name + ext)).isFile();
      } catch (err) {
        if (err.code === "ENOENT" || err.code === "ENOTDIR" || err.code === "EACCES") return false;
        throw err;
      }
    }));
}

/**
 * PATH 경고 줄. 진입점이 PATH를 넘긴 경우에만 검사한다.
 *
 * @param {{ searchPath?: string, pathExt?: string }} deps
 * @returns {string[]}
 */
function pathWarning(deps) {
  if (typeof deps.searchPath !== "string") return [];
  if (onPath("anchormind", deps.searchPath, deps.pathExt ?? "")) return [];
  return ["Warning: anchormind was not found on PATH. The plugin hooks run `anchormind hook`; install it before using the plugin.", ""];
}

/**
 * 인자 검사와 기본값
 *
 * @param {object} args
 * @param {{ homedir: () => string }} deps
 * @returns {{ target: string, dir: string, url?: string, write: boolean, force: boolean }}
 */
function resolveOptions(args, deps) {
  if (args.key !== undefined) throw new InitError("init does not take an API key; see --help for where the key goes");
  const target = args.target;
  const spec   = targetSpec(target);
  if (args.dir === true || args.url === true) throw new InitError("--dir and --url need a value");
  const dir = path.resolve(typeof args.dir === "string" ? args.dir : path.join(deps.homedir(), ".anchormind", spec.homeDir));
  return { target, dir, url: args.url, write: args.write === true, force: args.force === true };
}

/** 표준 출력. 처음 쓸 때 만들며, 받는 쪽이 닫히면 더 쓰지 않는다. */
let stdoutOutput = null;
const writeStdout = (text) => {
  stdoutOutput ??= createOutput(process.stdout);
  stdoutOutput.write(text);
};

const DEFAULT_DEPS = Object.freeze({
  stdout : writeStdout,
  homedir: () => os.homedir(),
  fs
});

/**
 * anchormind init --target <claude|codex>
 *
 * @param {object} args
 * @param {Partial<typeof DEFAULT_DEPS> & { searchPath?: string, pathExt?: string }} [overrides]
 *   진입점이 넘기는 PATH 정보와 시험용 의존성
 */
export default async function init(args, overrides = {}) {
  const deps    = { ...DEFAULT_DEPS, ...overrides };
  const options = resolveOptions(args, deps);
  const plan    = planInit(options);
  const entries = compareWithDisk(plan);
  const mode    = options.write ? "write" : "dry run";
  const steps   = ["Next steps:", ...plan.nextSteps.map(s => `  ${s}`), ""];

  deps.stdout([`anchormind init --target ${plan.target} (${mode})`, `Directory: ${plan.dir}`, ...renderReport(entries), ""].join("\n"));

  if (!options.write) {
    deps.stdout(["No files written. Run again with --write to create them.", "", ...pathWarning(deps), ...steps].join("\n"));
    return;
  }

  assertWritable(entries, options.force, deps.fs);
  const written = writeEntries(entries, deps.fs);
  deps.stdout([`Wrote ${written} file(s).`, "", ...pathWarning(deps), ...steps].join("\n"));
}
